package AdventUtils;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Scanner;

public final class FileUtils {

    private FileUtils() {
    }

    public static Scanner scanFromFile(String path) {

        try {

            return new Scanner(new File(path));

        } catch (FileNotFoundException e) {
            throw new RuntimeException("Could not open file: " + path, e);
        }

    }

    /* Lines 29 to 38 was suggested/generated by VS Code Copilot */

    public static List<String> readLines(String path) {
        try {
            return Files.readAllLines(Path.of(path), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new RuntimeException("Could not read lines from file: " + path, e);
        }
    }

    public static String readAll(String path) {
        try {
            return String.join("\n", readLines(path));
        } catch (RuntimeException e) {
            throw e;
        }
    }

}